config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  
  resources :meals
  resources :foods
  resources :ingredients
  
  namespace :admin do
    root "admin#index"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  has_rich_text :notes
  validates :name, :serving_size, :carbs, presence: true

  def calculate_carbs(quantity)
    (quantity.fdiv(self.serving_size) * self.carbs).round
  end
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :meal
  belongs_to :food

  validates :quantity, presence: true
end

app/models/meal.rb
class Meal < ApplicationRecord
  has_rich_text :notes
  has_many :ingredients
  has_many :foods, through: :ingredients

  validates :name, presence: true

  def calculate_carbs
    foods.sum { |food| food.calculate_carbs(ingredients.find_by(food: food).quantity)}
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[ show edit update destroy ]

  def index
    @foods = Food.all
  end
  
  def show
  end
  
  def new
    @food = Food.new
  end
  
  def create
    @food = Food.new(food_params)
    if @food.save
      redirect_to @food
    else
      render :new, status: :unprocessable_entity
    end
  end
  
  def edit
  end
  
  def update
    if @food.update(food_params)
      redirect_to @food
    else
      render :edit, status: :unprocessable_entity
    end
  end
  
  def destroy
    @food.destroy
    redirect_to foods_path
  end
  
  private
    def set_food
      @food = Food.find(params[:id])
    end

    def food_params
      params.expect(food: [ :name, :serving_size, :carbs, :notes ])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
    @ingredients = Ingredient.all
  end
  
  def show
    @ingredient = Ingredient.find(params[:id])
  end
  
  def new
    @ingredient = Ingredient.new
  end
  
  def create
    @ingredient = Ingredient.new(ingredient_params)
    if @ingredient.save
      redirect_to @ingredient
    else
      render :new, status: :unprocessable_entity
    end
  end
  
  def updated_at
    @ingredient = Ingredient.find(params[:id])
    if @ingredient.update(ingredient_params)
      redirect_to @ingredient
    else
      render :edit, status: :unprocessable_entity
    end
  end
  
  private
    def ingredient_params
      params.expect(ingredient: [ :quantity, :meal_id, :food_id ])
    end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  def index
    @meals = Meal.all
  end
  
  def show
    @meal = Meal.find(params[:id])
  end
  
  def new
    @meal = Meal.new
  end
  
  def create
    @meal = Meal.new(meal_params)
    if @meal.save
      redirect_to @meal
    else
      render :new, status: :unprocessable_entity
    end
  end
  
  def updated_at
    @meal = Meal.find(params[:id])
    if @meal.update(meal_params)
      redirect_to @meal
    else
      render :edit, status: :unprocessable_entity
    end
  end
  
  private
    def meal_params
      params.expect(meal: [ :name, :notes ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/foods/_form.html.erb
<%= form_with model: food do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :serving_size %>
    <%= form.number_field :serving_size %>
  </div>
  <div>
    <%= form.label :carbs %>
    <%= form.number_field :carbs %>
  </div>
  <div>
    <%= form.label :notes, style: "display block" %>
    <%= form.rich_text_area :notes %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Edit food</h1>
<%= render "form", food: @food %>
<%= link_to "Cancel", foods_path %>

app/views/foods/index.html.erb
<h1>Foods</h1>
<%= link_to "New food", new_food_path %>
<div id="foods">
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Serving Size</th>
        <th>Carbs</th>
        <th>Notes</th>
        <th>Edit</th>
      </tr>
    </thead>
    <tbody>
      <% @foods.each do |food| %>
        <tr>
          <td>
            <%= link_to food.name, food %>
          </td>
          <td>
            <%= food.serving_size %>g
          </td>
          <td>
            <%= food.carbs %>g
          </td>
          <td>
            <%= food.notes %>
          </td>
          <td>
            <%= link_to "Edit", edit_food_path(food) %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </div>

app/views/foods/new.html.erb
<h1>New food</h1>
<%= render "form", food: @food %>
<%= link_to "Cancel", foods_path %>

app/views/foods/show.html.erb
<% cache @food do %>
  <h1><%= @food.name %></h1>
  <div id="food">
    <table>
      <thead>
        <tr>
          <th>Serving Size</th>
          <th>Carbs</th>
          <th>Notes</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= @food.serving_size %>g</td>
          <td><%= @food.carbs %>g</td>
          <td><%= @food.notes %></td>
        </tr>
      </tbody>
    </table>
  </div>
  <%= link_to "Back", foods_path %>
  <%= link_to "Edit", edit_food_path(@food) %>
  <%= button_to "Delete", @food, method: :delete, data: { turbo_confirm: "Are you sure?" } %>
<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/ingredients/index.html.erb
<h1>Ingredients</h1>

<div id="ingredients">
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Quantity</th>
        <th>Carbs</th>
      </tr>
    </thead>
    <tbody>
      <% @ingredients.each do |ingredient| %>
        <tr>
          <td>
            <%= link_to ingredient.food.name, ingredient %>
          </td>
          <td>
            <%= ingredient.quantity %>g
          </td>
          <td>
            <%= ingredient.food.calculate_carbs(ingredient.quantity) %>g
          </td>
        </tr>    
      <% end %>
    </tbody>
</div>

app/views/ingredients/show.html.erb
<h1><%= @ingredient.food.name %></h1>

<%= link_to "Back", ingredients_path %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Carb Counter" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/meals/index.html.erb
<h1>Meals</h1>

<div id="meals">
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Ingredients</th>
        <th>Carbs</th>
      </tr>
    </thead>
    <tbody>
      <% @meals.each do |meal| %>
        <tr>
          <td>
            <%= link_to meal.name, meal %>
          </td>
          <td>
            <%= meal.calculate_carbs %>g
          </td>
        </tr>    
      <% end %>
    </tbody>
</div>

app/views/meals/show.html.erb
<h1><%= @meal.name %></h1>
<%= link_to "Back", meals_path %>